### PR TITLE
Update read_punch.pro

### PR DESCRIPTION
**Pull request by lowderchris**
Renamed tfiles to reflect singular file usage.
Added a return statement.

### CODE REVIEW

**Review by jmbhughes — COMMENTED** [review]
What does the t in `tfile` mean?

**Comment by jmbhughes** [comment]
Also it returns nothing?

**Comment by jmbhughes** [comment]
@s0larish could you test this? I don't know how to set up automated testing for IDL, so we'll have to just wing it for now.

**Comment by lowderchris** [comment]
Matt and I tested this real quick, and it does look like you might *not* need the return statement at the end after all. But I'm not as well versed in IDL, so someone else should have the final say there. Matt also added a more verbose example call in the docstring.

**Comment by s0larish** [comment]
> What does the t in `tfile` mean?
't' for 'tile-compressed'

**Review by s0larish — APPROVED** [review]

**Pull request merged**
